name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run compile
      run: sbt compile
    - name: Run test coverage
      run: sbt -Dsbt.log.noformat=true clean coverage test
    - name: Run test report
      run: sbt -Dsbt.log.noformat=true coverageReport
    - name: Run sonar
      run: sbt scalastyle
    - name: Run packacge
      run: sbt package
      

